server:
  port: 1234

spring:
  application:
    name: customer-api
  datasource:
    username: wen.yu@helium10.com
    password: "#fk+0z*V7@lVzJG("
    url: jdbc:postgresql://helium10-main-rds.helium-staging.com:5432/dba
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456
    virtual-host: vhost_local
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
mybatis-plus:
  mapper-locations: "classpath:/mappers/**/*.xml"