areDownloadMobileAppBannersShown: false
adminEmail: admin@example.com
plansOptions:
  Helium10_Free:
    interval: month
    intervalCount: 1
  Helium10_Starter_39:
    interval: month
    intervalCount: 1
    showIfPlanIs:
      Helium10_Free:
        - Helium10_Starter
        - Helium10_Starter_39