package com.pacvue.h10.customer.api.infrastructure.helper;

import java.util.HashMap;
import java.util.Map;

public class PlansMapHelper {

    public static final Map<String, String> H10_TO_STRIPE = new HashMap<>() {{
        put(PlansHelper.HELIUM10_FREE_PLAN, PlansHelper.HELIUM10_FREE_PLAN);

    }};

//    PlansHelper.HELIUM10_FREE_PLAN => PlansHelper.HELIUM10_FREE_PLAN,
//    PlansHelper.HELIUM10_STARTER_PLAN => YII2_STARTER_MONTHLY_STRIPE_PRICE,
//    PlansHelper.HELIUM10_STARTER_ANNUAL_PLAN => YII2_STARTER_ANNUAL_STRIPE_PRICE,
//    PlansHelper.HELIUM10_STARTER_39_PLAN => YII2_STARTER_MONTHLY_39_STRIPE_PRICE,
//    PlansHelper.HELIUM10_STARTER_ANNUAL_339_PLAN => YII2_STARTER_ANNUAL_339_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_PLAN => PlansHelper.HELIUM10_A_LA_CARTE_PLAN,
//    PlansHelper.HELIUM10_A_LA_CARTE_ANNUAL_PLAN => PlansHelper.HELIUM10_A_LA_CARTE_ANNUAL_PLAN,
//    PlansHelper.HELIUM10_PLATINUM_PLAN => PlansHelper.HELIUM10_GOLD_PLAN,
//    PlansHelper.HELIUM10_PLATINUM_ANNUAL_PLAN => PlansHelper.HELIUM10_GOLD_ANNUAL_PLAN,
//    PlansHelper.HELIUM10_PLATINUM_99_PLAN => YII2_PLATINUM_MONTHLY_99_STRIPE_PRICE,
//    PlansHelper.HELIUM10_PLATINUM_ANNUAL_999_PLAN => YII2_PLATINUM_ANNUAL_999_STRIPE_PRICE,
//    PlansHelper.HELIUM10_DIAMOND_PLAN => PlansHelper.HELIUM10_PLATINUM_PLAN,
//    PlansHelper.HELIUM10_DIAMOND_ANNUAL_PLAN => PlansHelper.HELIUM10_PLATINUM_ANNUAL_PLAN,
//    PlansHelper.HELIUM10_DIAMOND_199_PLAN => YII2_DIAMOND_MONTHLY_199_STRIPE_PRICE,
//    PlansHelper.HELIUM10_DIAMOND_ANNUAL_1999_PLAN => YII2_DIAMOND_ANNUAL_1999_STRIPE_PRICE,
//    PlansHelper.HELIUM10_DIAMOND_249_PLAN => YII2_DIAMOND_MONTHLY_249_STRIPE_PRICE,
//    PlansHelper.HELIUM10_DIAMOND_ANNUAL_2499_PLAN => YII2_DIAMOND_ANNUAL_2499_STRIPE_PRICE,
//    PlansHelper.HELIUM10_ELITE_PLAN => PlansHelper.HELIUM10_ELITE_PLAN,
//    PlansHelper.HELIUM10_ELITE_399_PLAN => YII2_ELITE_MONTHLY_399_STRIPE_PRICE,
//    PlansHelper.HELIUM10_ELITE_QUARTER_PLAN => YII2_ELITE_QUARTERLY_STRIPE_PRICE,
//    PlansHelper.HELIUM10_ELITE_ANNUAL_PLAN => YII2_ELITE_ANNUAL_STRIPE_PRICE,
//    PlansHelper.HELIUM10_START_YOUR_BUSINESS_PLAN => YII2_START_YOUR_BUSINESS_MONTHLY_STRIPE_PRICE,
//    PlansHelper.HELIUM10_START_YOUR_BUSINESS_QUARTER_PLAN => YII2_START_YOUR_BUSINESS_QUARTERLY_STRIPE_PRICE,
//    PlansHelper.HELIUM10_START_YOUR_BUSINESS_ANNUAL_PLAN => YII2_START_YOUR_BUSINESS_ANNUAL_STRIPE_PRICE,
//    PlansHelper.HELIUM10_SCALE_YOUR_BUSINESS_PLAN => YII2_SCALE_YOUR_BUSINESS_MONTHLY_STRIPE_PRICE,
//    PlansHelper.HELIUM10_SCALE_YOUR_BUSINESS_QUARTER_PLAN => YII2_SCALE_YOUR_BUSINESS_QUARTERLY_STRIPE_PRICE,
//    PlansHelper.HELIUM10_SCALE_YOUR_BUSINESS_ANNUAL_PLAN => YII2_SCALE_YOUR_BUSINESS_ANNUAL_STRIPE_PRICE,
//    PlansHelper.HELIUM10_SUPERCHARGE_YOUR_BRAND_PLAN => YII2_SUPERCHARGE_YOUR_BRAND_MONTHLY_STRIPE_PRICE,
//    PlansHelper.HELIUM10_SUPERCHARGE_YOUR_BRAND_QUARTER_PLAN => YII2_SUPERCHARGE_YOUR_BRAND_QUARTERLY_STRIPE_PRICE,
//    PlansHelper.HELIUM10_SUPERCHARGE_YOUR_BRAND_ANNUAL_PLAN => YII2_SUPERCHARGE_YOUR_BRAND_ANNUAL_STRIPE_PRICE,
//    PlansHelper.HELIUM10_ADTOMIC_AND_SCALE_YOUR_BUSINESS_BUNDLE => YII2_ADTOMIC_SCALE_YOUR_BUSINESS_BUNDLE_MONTHLY_STRIPE_PRICE,
//    PlansHelper.HELIUM10_ADTOMIC_AND_SCALE_YOUR_BUSINESS_BUNDLE_ANNUAL => YII2_ADTOMIC_SCALE_YOUR_BUSINESS_BUNDLE_ANNUAL_STRIPE_PRICE,
//
//    // A La Carte
//    PlansHelper.HELIUM10_A_LA_CARTE_BLACKBOX_39 => YII2_ALC_BB_MONTHLY_39_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_BLACKBOX_ANNUAL_390 => YII2_ALC_BB_ANNUAL_390_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_CEREBRO_39 => YII2_ALC_CEREBRO_MONTHLY_39_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_CEREBRO_ANNUAL_390 => YII2_ALC_CEREBRO_ANNUAL_390_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_KT_59 => YII2_ALC_KT_MONTHLY_59_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_KT_ANNUAL_590 => YII2_ALC_KT_ANNUAL_590_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_MAGNET_39 => YII2_ALC_MAGNET_MONTHLY_39_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_MAGNET_ANNUAL_390 => YII2_ALC_MAGNET_ANNUAL_390_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_IC_19 => YII2_ALC_IC_MONTHLY_19_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_IC_ANNUAL_190 => YII2_ALC_IC_ANNUAL_190_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_ALERTS_39 => YII2_ALC_ALERTS_MONTHLY_39_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_ALERTS_ANNUAL_390 => YII2_ALC_ALERTS_ANNUAL_390_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_RG_99 => YII2_ALC_RG_MONTHLY_99_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_RG_ANNUAL_990 => YII2_ALC_RG_ANNUAL_990_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_XRAY_19 => YII2_ALC_XRAY_MONTHLY_19_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_XRAY_ANNUAL_190 => YII2_ALC_XRAY_ANNUAL_190_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_PROFITS_39 => YII2_ALC_PROFITS_MONTHLY_39_STRIPE_PRICE,
//    PlansHelper.HELIUM10_A_LA_CARTE_PROFITS_ANNUAL_390 => YII2_ALC_PROFITS_ANNUAL_390_STRIPE_PRICE,
//
//    // Chinese plans
//    PlansHelper.HELIUM10_EXPLORER_CN => YII2_STARTER_CN_MONTHLY_STRIPE_PRICE,
//    PlansHelper.HELIUM10_EXPLORER_CN_ANNUAL => YII2_STARTER_CN_ANNUAL_STRIPE_PRICE,
//    PlansHelper.HELIUM10_ENTREPRENEUR_CN => YII2_PLATINUM_CN_MONTHLY_STRIPE_PRICE,
//    PlansHelper.HELIUM10_ENTREPRENEUR_CN_ANNUAL => YII2_PLATINUM_CN_ANNUAL_STRIPE_PRICE,
//    PlansHelper.HELIUM10_PROFESSIONAL_CN => YII2_DIAMOND_CN_MONTHLY_STRIPE_PRICE,
//    PlansHelper.HELIUM10_PROFESSIONAL_CN_ANNUAL => YII2_DIAMOND_CN_ANNUAL_STRIPE_PRICE,
//
//    // Follow-Up Boosters
//    PlansHelper.HELIUM10_FOLLOW_UP_BEGINNER => YII2_FOLLOW_UP_BEGINNER_STRIPE_PRICE,
//    PlansHelper.HELIUM10_FOLLOW_UP_PRO => YII2_FOLLOW_UP_PRO_STRIPE_PRICE,
//    PlansHelper.HELIUM10_FOLLOW_UP_ENTERPRISE => YII2_FOLLOW_UP_ENTERPRISE_STRIPE_PRICE,
//            ];

    /**
     * @return string
     */
    public static String getStripePlanId(String heliumPlanId) {
        return H10_TO_STRIPE.getOrDefault(heliumPlanId, heliumPlanId);
    }
}
